### PR TITLE
Add unit test using Persimmon

### PR DESCRIPTION
**Pull request by myokoym**
I'm trying to add Config type unit test.
I don't know how to test for F#. I'm trying [Persimmon](http://persimmon-projects.github.io/Persimmon/).
I reffered to [Persimmon.Demo](https://github.com/persimmon-projects/Persimmon.Demo).

Related to #3.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Fantastic work! :heart_eyes: 
But, this PR seems to be created with Visual Studio 2015. (Perhaps, community edition?)
In your environment, this added test works well?

**Comment by myokoym** [comment]
> But, this PR seems to be created with Visual Studio 2015. (Perhaps, community edition?)

Yes, I'm using Visual Studio Community 2015. I should use Visual Studio Express 2013? 

> In your environment, this added test works well?

The result in my environment is the following:

```
PS C:\Users\myokoym\Documents\GitHub\grnline.fs> .\RunTests.ps1
...
ビルドに成功しました。
    0 個の警告
    0 エラー

経過時間 00:00:02.58
x
Assertion Violated: path test
1. Expect: "\path\to\groonga"
   Actual: "C:\groonga-5.1.0-x64\groonga-5.1.0-x64\bin\groonga.exe"
============================== summary ===============================
run: 1, error: 0, violated: 1, skipped: 0, duration: 00:00:00.0235568
```

**Comment by cosmo0920** [comment]
Thanks for your answer.

> I should use Visual Stdio Express 2013? 

Perhaps, yes. But not mandatory to use it to create PR.

> The result in my environment is the following:

Oh, the test case seems to be failing!! :cold_sweat:

**Comment by cosmo0920** [comment]
BTW, why do you use `Persimmon`?
(I suspect that `Persimmon` project provides documents in Japanese. :smiley: )

**Comment by cosmo0920** [comment]
I've committed https://github.com/cosmo0920/grnline.fs/commit/68ec57d593754ea07b9aef2b9e41442495c59c37 to follow up this PR.
Anyway, thanks contribution in this project!! 
You are an excellent F# newbie! :sunrise_over_mountains:

**Pull request merged**
